> Projeto Desenvolve <br>
Programação Intermediária com Python <br>
Profa. Camila Laranjeira (mila@projetodesenvolve.com.br) <br>

# 3.6 - Pandas

## Exercícios
Antes de continuar, baixe os arquivos das bases de dados de partidas em Copas do Mundo e salve na mesma pasta deste notebook.
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1930_2022.csv
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1991_2023.csv

A célula a seguir já carrega os dados em CSV e ajusta as colunas para trabalharmos com os nomes traduzidos (como fizemos em aula).

In [1]:
import pandas as pd

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',12)

wcwomen_df = pd.read_csv('matches_1991_2023.csv')
wcmen_df   = pd.read_csv('matches_1930_2022.csv')
wc = pd.concat((wcwomen_df,wcmen_df)).reset_index()

nomes_traduzidos = {'home_team': 'time_1', 'away_team': 'time_2', 'home_score': 'gols_1', 'away_score': 'gols_2',
                    'Date': 'data', 'Year': 'ano', 'Host': 'país_sede', 'Attendance': 'comparecimento',
                    'Score': 'resultado', 'Round': 'rodada', 'home_goal': 'gols_1_detalhes', 'away_goal': 'gols_2_detalhes',
                    'home_own_goal': 'gols_1_contra', 'away_own_goal': 'gols_2_contra',
                    'home_penalty_goal': 'gols_1_penalti', 'away_penalty_goal': 'gols_2_penalti',
                    'home_red_card': 'cartao_vermelho_1', 'away_red_card': 'cartao_vermelho_2',
                    'home_yellow_card_long': 'cartao_amarelo_1', 'away_yellow_card_long': 'cartao_amarelo_2'}

wc = wc.loc[:, nomes_traduzidos.keys()]
wc.columns = nomes_traduzidos.values()

copa = wc['ano'].apply( lambda x: 'Masculina' if x % 2 == 0 else 'Feminina').astype('string')
wc['copa'] = copa
display(wc)

,time_1,time_2,gols_1,gols_2,data,ano,país_sede,comparecimento,resultado,rodada,gols_1_detalhes,gols_2_detalhes,gols_1_contra,gols_2_contra,gols_1_penalti,gols_2_penalti,cartao_vermelho_1,cartao_vermelho_2,cartao_amarelo_1,cartao_amarelo_2,copa
0,Spain,England,1,0,2023-08-20,2023,"Australia, New Zealand",75784,1–0,Final,Olga Carmona · 29’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['78’|1:0|Salma Paralluelo'],['55’|1:0|Lauren Hemp'],Feminina
1,Sweden,Australia,2,0,2023-08-19,2023,"Australia, New Zealand",49461,2–0,Third-place match,Kosovare Asllani · 62’,NaN,NaN,NaN,Fridolina Rolfö (P) · 30’,NaN,NaN,NaN,"['88’|2:0|Elin Rubensson', '90+5’|2:0|Lina Hur...",['45+1’|1:0|Katrina Gorry'],Feminina
2,Australia,England,1,3,2023-08-16,2023,"Australia, New Zealand",75784,1–3,Semi-finals,Sam Kerr · 63’,Ella Toone · 36’|Lauren Hemp · 71’|Alessia Rus...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['10’|0:0|Alex Greenwood', '90+5’|1:3|Chloe Ke...",Feminina
3,Spain,Sweden,2,1,2023-08-15,2023,"Australia, New Zealand",43217,2–1,Semi-finals,Salma Paralluelo · 81’|Olga Carmona · 89’,Rebecka Blomqvist · 88’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Feminina
4,Australia,France,0,0,2023-08-12,2023,"Australia, New Zealand",49461,(7) 0–0 (6),Quarter-finals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['92’|0:0|Katrina Gorry'],NaN,Feminina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,Argentina,France,1,0,1930-07-15,1930,Uruguay,23409,1–0,Group stage,Luis Monti · 81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1308,Yugoslavia,Brazil,2,1,1930-07-14,1930,Uruguay,24059,2–1,Group stage,Aleksandar Tirnanić · 21|Ivan Bek · 30,Preguinho · 62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1309,Romania,Peru,3,1,1930-07-14,1930,Uruguay,2549,3–1,Group stage,Adalbert Deșu · 1|Constantin Stanciu · 79|Nico...,Luis de Souza Ferreira · 75,NaN,NaN,NaN,NaN,NaN,Plácido Galindo · 70,NaN,NaN,Masculina
1310,United States,Belgium,3,0,1930-07-13,1930,Uruguay,18346,3–0,Group stage,Bart McGhee · 23|Tom Florie · 45|Bert Patenaud...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1311,France,Mexico,4,1,1930-07-13,1930,Uruguay,4444,4–1,Group stage,Lucien Laurent · 19|Marcel Langiller · 40|Andr...,Juan Carreño · 70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina

#### Q1.
Faça as conversões de tipo necessárias para que a saída do comando `wc.info()` seja como apresentado a seguir. E **salve o novo dataframe** com o comando `df.to_csv('wc_formatado.csv')`.

```
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   time_1             1312 non-null   string        
 1   time_2             1312 non-null   string        
 2   gols_1             1312 non-null   int64         
 3   gols_2             1312 non-null   int64         
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64         
 6   país_sede          1312 non-null   string        
 7   comparecimento     1312 non-null   int64         
 8   resultado          1312 non-null   string        
 9   rodada             1312 non-null   category      
 10  gols_1_detalhes    970 non-null    string        
 11  gols_2_detalhes    771 non-null    string        
 12  gols_1_contra      57 non-null     string        
 13  gols_2_contra      30 non-null     string        
 14  gols_1_penalti     170 non-null    string        
 15  gols_2_penalti     119 non-null    string        
 16  cartao_vermelho_1  59 non-null     string        
 17  cartao_vermelho_2  65 non-null     string        
 18  cartao_amarelo_1   834 non-null    string        
 19  cartao_amarelo_2   857 non-null    string        
 20  copa               1312 non-null   string 
```

In [2]:
import pandas as pd
from IPython.display import display

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 12)

wcwomen_df = pd.read_csv('matches_1991_2023.csv')
wcmen_df = pd.read_csv('matches_1930_2022.csv')

wc = pd.concat((wcwomen_df, wcmen_df), ignore_index=True)

nomes_traduzidos = {
    'home_team': 'time_1',
    'away_team': 'time_2',
    'home_score': 'gols_1',
    'away_score': 'gols_2',
    'Date': 'data',
    'Year': 'ano',
    'Host': 'país_sede',
    'Attendance': 'comparecimento',
    'Score': 'resultado',
    'Round': 'rodada',
    'home_goal': 'gols_1_detalhes',
    'away_goal': 'gols_2_detalhes',
    'home_own_goal': 'gols_1_contra',
    'away_own_goal': 'gols_2_contra',
    'home_penalty_goal': 'gols_1_penalti',
    'away_penalty_goal': 'gols_2_penalti',
    'home_red_card': 'cartao_vermelho_1',
    'away_red_card': 'cartao_vermelho_2',
    'home_yellow_card_long': 'cartao_amarelo_1',
    'away_yellow_card_long': 'cartao_amarelo_2'
}

wc = wc[list(nomes_traduzidos.keys())]
wc.columns = list(nomes_traduzidos.values())

wc['copa'] = wc['ano'].apply(
    lambda x: 'Masculina' if x % 2 == 0 else 'Feminina'
)

wc = wc.astype({
    'time_1': 'string',
    'time_2': 'string',
    'gols_1': 'int64',
    'gols_2': 'int64',
    'ano': 'int64',
    'país_sede': 'string',
    'comparecimento': 'int64',
    'resultado': 'string',
    'rodada': 'category',
    'gols_1_detalhes': 'string',
    'gols_2_detalhes': 'string',
    'gols_1_contra': 'string',
    'gols_2_contra': 'string',
    'gols_1_penalti': 'string',
    'gols_2_penalti': 'string',
    'cartao_vermelho_1': 'string',
    'cartao_vermelho_2': 'string',
    'cartao_amarelo_1': 'string',
    'cartao_amarelo_2': 'string',
    'copa': 'string'
})

wc['data'] = pd.to_datetime(wc['data'])

wc.to_csv('wc_formatado.csv', index=False)


display(wc)

,time_1,time_2,gols_1,gols_2,data,ano,país_sede,comparecimento,resultado,rodada,gols_1_detalhes,gols_2_detalhes,gols_1_contra,gols_2_contra,gols_1_penalti,gols_2_penalti,cartao_vermelho_1,cartao_vermelho_2,cartao_amarelo_1,cartao_amarelo_2,copa
0,Spain,England,1,0,2023-08-20,2023,"Australia, New Zealand",75784,1–0,Final,Olga Carmona · 29’,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,['78’|1:0|Salma Paralluelo'],['55’|1:0|Lauren Hemp'],Feminina
1,Sweden,Australia,2,0,2023-08-19,2023,"Australia, New Zealand",49461,2–0,Third-place match,Kosovare Asllani · 62’,<NA>,<NA>,<NA>,Fridolina Rolfö (P) · 30’,<NA>,<NA>,<NA>,"['88’|2:0|Elin Rubensson', '90+5’|2:0|Lina Hur...",['45+1’|1:0|Katrina Gorry'],Feminina
2,Australia,England,1,3,2023-08-16,2023,"Australia, New Zealand",75784,1–3,Semi-finals,Sam Kerr · 63’,Ella Toone · 36’|Lauren Hemp · 71’|Alessia Rus...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"['10’|0:0|Alex Greenwood', '90+5’|1:3|Chloe Ke...",Feminina
3,Spain,Sweden,2,1,2023-08-15,2023,"Australia, New Zealand",43217,2–1,Semi-finals,Salma Paralluelo · 81’|Olga Carmona · 89’,Rebecka Blomqvist · 88’,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Feminina
4,Australia,France,0,0,2023-08-12,2023,"Australia, New Zealand",49461,(7) 0–0 (6),Quarter-finals,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,['92’|0:0|Katrina Gorry'],<NA>,Feminina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,Argentina,France,1,0,1930-07-15,1930,Uruguay,23409,1–0,Group stage,Luis Monti · 81,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Masculina
1308,Yugoslavia,Brazil,2,1,1930-07-14,1930,Uruguay,24059,2–1,Group stage,Aleksandar Tirnanić · 21|Ivan Bek · 30,Preguinho · 62,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Masculina
1309,Romania,Peru,3,1,1930-07-14,1930,Uruguay,2549,3–1,Group stage,Adalbert Deșu · 1|Constantin Stanciu · 79|Nico...,Luis de Souza Ferreira · 75,<NA>,<NA>,<NA>,<NA>,<NA>,Plácido Galindo · 70,<NA>,<NA>,Masculina
1310,United States,Belgium,3,0,1930-07-13,1930,Uruguay,18346,3–0,Group stage,Bart McGhee · 23|Tom Florie · 45|Bert Patenaud...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Masculina
1311,France,Mexico,4,1,1930-07-13,1930,Uruguay,4444,4–1,Group stage,Lucien Laurent · 19|Marcel Langiller · 40|Andr...,Juan Carreño · 70,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Masculina

#### Q2.
Apresente a linha do dataframe `wc` que corresponde ao jogo com maior audiência da história.

In [3]:
import pandas as pd

wc = pd.read_csv('wc_formatado.csv')

print(wc.loc[[wc['comparecimento'].idxmax()]])

       time_1  time_2  gols_1  gols_2        data   ano país_sede  \
1238  Uruguay  Brazil       2       1  1950-07-16  1950    Brazil

      comparecimento resultado       rodada  \
1238          173850       2–1  Final stage

                                        gols_1_detalhes gols_2_detalhes  \
1238  Juan Alberto Schiaffino · 66|Alcides Ghiggia · 79     Friaça · 47

     gols_1_contra gols_2_contra gols_1_penalti gols_2_penalti  \
1238           NaN           NaN            NaN            NaN

     cartao_vermelho_1 cartao_vermelho_2 cartao_amarelo_1 cartao_amarelo_2  \
1238               NaN               NaN              NaN              NaN

           copa
1238  Masculina

#### Q3.
Aplicando operações sobre as colunas `ano` e `copa` do dataframe `wc`, apresente quantas copas femininas e quantas copas masculinas já aconteceram na história.

Exemplo de saída (valores inventados):
```
Masculina: 22
Feminina: 9
```

In [4]:
import pandas as pd

wc = pd.read_csv('wc_formatado.csv')

copas = wc.groupby('copa')['ano'].nunique()

print(f"Masculina: {copas['Masculina']}")
print(f"Feminina: {copas['Feminina']}")

Masculina: 22
Feminina: 9

#### Q3. 
Crie um dataframe `participacao` com as colunas `país`, `copa`, e `num_copas` que armazena a quantidade de copas do mundo que cada país participou, informando se é da copa masculina ou feminina. Ao final imprima, como apresentado a seguir, o top 5 países de cada competição que mais participou de copas do mundo.

Exemplo de saída (valores inventados):
```
país            copa        num_copas
Brazil          Feminina    8
Unites States   Feminina    8
Germany         Feminina    8
Japan           Feminina    7
Colombia        Feminina    7
```

```
país            copa        num_copas
Brazil          Masculina   21
Germany         Masculina   21
Argentina       Masculina   20
England         Masculina   20
Mexico          Masculina   20
```

In [5]:
import pandas as pd

# Cria um dataframe com todos os participantes

wc = pd.read_csv('wc_formatado.csv')

participantes = pd.concat([
    wc[['ano', 'copa', 'time_1']].rename(columns={'time_1': 'país'}),
    wc[['ano', 'copa', 'time_2']].rename(columns={'time_2': 'país'})
])

participantes = participantes.drop_duplicates(
    subset=['ano', 'copa', 'país']
)

# Conta quantas copas cada país participou
participacao = (
    participantes
    .groupby(['país', 'copa'])
    .size()
    .reset_index(name='num_copas')
)

print("TOP 5 - COPA FEMININA")
print(
    participacao[participacao['copa'] == 'Feminina']
    .sort_values('num_copas', ascending=False)
    .head(5)
)

print()

print("TOP 5 - COPA MASCULINA")
print(
    participacao[participacao['copa'] == 'Masculina']
    .sort_values('num_copas', ascending=False)
    .head(5)
)

TOP 5 - COPA FEMININA
       país      copa  num_copas
10   Brazil  Feminina          9
81   Norway  Feminina          9
63    Japan  Feminina          9
45  Germany  Feminina          9
78  Nigeria  Feminina          9

TOP 5 - COPA MASCULINA
         país       copa  num_copas
11     Brazil  Masculina         22
3   Argentina  Masculina         18
60      Italy  Masculina         18
71     Mexico  Masculina         17
40    England  Masculina         16

#### Q4. 
* Crie um dataframe `gols` com duas colunas `país` e `total_gols` com o total de gols marcados por cada país durante todas as copas do mundo, juntando gols em casa (`gols_1`) e gols como time visitante (`gols_2`).
* Imprima o dataframe `gols` ordenado de forma decrescente, para que os times com mais gols fiquem no topo.

Segue um exemplo ilustrativo com o formato do dataframe resultado:

```
país        total_gols
Brazil      120
Argentina   112
Germany     107
...
```

In [6]:
gols_fora = (
    wc.groupby('time_2')['gols_2']
    .sum()
    .reset_index()
    .rename(columns={
        'time_2': 'país',
        'gols_2': 'total_gols'
    })
)

gols = pd.concat([gols_casa, gols_fora])

# Soma os gols totais por país
gols = (
    gols.groupby('país')['total_gols']
    .sum()
    .reset_index()
)

# Ordena do maior para o menor
gols = gols.sort_values(
    by='total_gols',
    ascending=False
)

# Exibe o resultado
print(gols)

NameError: name 'gols_casa' is not defined

#### Q5. 
Qual país tomou mais cartões amarelos somando todas as copas?

Neste exercício você vai trabalhar com as colunas `cartao_amarelo_1` e `cartao_amarelo_2` onde cada observação é uma string represetando uma lista dos cartões amarelos de um único jogo na forma `minuto|placar|jogador(a)`. Por exemplo:
```
['16’|1:0|Rosana Gómez', '20’|2:0|Gabriela Chávez]
```

Recomendo criar colunas `num_cartoes_1` e `num_cartoes_2` a partir de cada coluna `cartao_amarelo_X` usando o método genérico `apply` para chamar uma função que você vai criar para transformar uma observação de cartão amarelo em uma contagem de elementos da lista. 

Lembre de levar em consideração que muitas observações são `NaN`. 

Em seguida faça sua mágica para agrupar as informações por país, acumular os cartões de jogos em casa e jogos visitante, e produzir o resultado final como apresentado a seguir (valores inventados):

```
país        cartões amarelos
Argentina   97
England     93
Australia   93
...
```

In [ ]:
import pandas as pd
import ast

wc = pd.read_csv('wc_formatado.csv')

def contar_cartoes(valor):
    if pd.isna(valor):
        return 0
    try:
        return len(ast.literal_eval(valor))
    except:
        return 0

cartoes = pd.concat([
    wc[['time_1', 'cartao_amarelo_1']]
        .assign(cartoes=lambda df: df['cartao_amarelo_1'].apply(contar_cartoes))
        .rename(columns={'time_1': 'país'})[['país', 'cartoes']],

    wc[['time_2', 'cartao_amarelo_2']]
        .assign(cartoes=lambda df: df['cartao_amarelo_2'].apply(contar_cartoes))
        .rename(columns={'time_2': 'país'})[['país', 'cartoes']]
])

cartoes = (
    cartoes.groupby('país')['cartoes']
    .sum()
    .reset_index(name='cartoes_amarelos')
    .sort_values('cartoes_amarelos', ascending=False)
)

print(cartoes)

#### Q6.
Qual o top10 jogadores com mais gols em copa? Considere gols em jogo e gols de pênalti.

Para conseguir essa informação, você precisará trabalhar com as colunas:
```
10  gols_1_detalhes         
11  gols_2_detalhes    
14  gols_1_penalti     
15  gols_2_penalti     
```

Essas também são colunas textuais, onde cada observações apresenta todos os gols de uma partida separados pelo caracter `|`. Cada gol está na forma `'Jogador(a) · minuto’'`. Por exemplo:
```
'Alex Morgan · 12’|Rose Lavelle · 20’'
```

Lembre de levar em consideração que muitas observações são `NaN`. 

Recomendo criar um dicionário à parte, onde cada chave será um jogador encontrado nessas colunas do dataframe `wc` e o valor correspondente será a contagem de ocorrências desses nomes.

Em seguida basta converter o seu dicionário em um dataframe e imprimí-lo na forma (valores não são inventados 😁):
```
jogador(a)      num_gols 
Marta           17
Miroslav Klose  16
... 
```

In [ ]:
import pandas as pd

wc = pd.read_csv('wc_formatado.csv')

artilheiros = {}

for coluna in [
    'gols_1_detalhes',
    'gols_2_detalhes',
    'gols_1_penalti',
    'gols_2_penalti'
]:

    for registro in wc[coluna].dropna():

        for gol in str(registro).split('|'):

            if '·' in gol:
                jogador = gol.split('·')[0].strip()

                artilheiros[jogador] = (
                    artilheiros.get(jogador, 0) + 1
                )

gols = (
    pd.DataFrame(
        list(artilheiros.items()),
        columns=['jogador(a)', 'num_gols']
    )
    .sort_values('num_gols', ascending=False)
)

print(gols.head(20))